spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  data:
    web:
      pageable:
        max-page-size: 50

  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 1000
            read-timeout: 5000
    function:
      definition: notifyDriversAboutNewRide;notifyAboutRideCancellation;notifyAboutRideFinished
    stream:
      bindings:
        notifyDriversAboutNewRide-in-0:
          destination: newRideTopic
          content-type: application/json
          group: drivers
        notifyAboutRideCancellation-in-0:
          destination: canceledRideTopic
          content-type: application/json
          group: drivers
        notifyAboutRideFinished-in-0:
          destination: finishedRideTopic
          content-type: application/json
          group: drivers
      kafka:
        binder:
          brokers: "${KAFKA_HOST}:${KAFKA_PORT}"
          enable-observation: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: cab-app
            client-secret: ${CAB_APP_CLIENT_SECRET}
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/cab-app-realm
          jwk-set-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/cab-app-realm/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
        "[resilience4j.circuitbreaker.calls]": true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans

logging:
  level:
    root: info
    liquibase: error

exception:
  handling:
    include: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        sliding-window-type: time-based
        sliding-window-size: 100
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 10
        wait-duration-in-open-state: 20s
        slow-call-duration-threshold: 4s
        slow-call-rate-threshold: 90
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
          - feign.RetryableException

token:
  converter:
    include: true
    principal-attribute: preferred_username
    resource-id: cab-app

keycloak:
  server-url: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}
  realm: cab-app-realm
