spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  data:
    web:
      pageable:
        max-page-size: 50
  
  cloud:
    stream:
      function:
        definition: createPayment
      bindings:
        createPayment-in-0:
          destination: passengerPayCardTopic
          content-type: application/json
          group: passengerPayCardCreating
        outCardPaymentCreated:
          destination: cardPaymentCreatedTopic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:29092

logging:
  level:
    root: info
    liquibase: error

exception:
  handling:
    include: true
