spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  cloud:
    function:
      definition: notifyAboutRideAcceptance
    stream:
      bindings:
        notifyAboutRideAcceptance-in-0:
          destination: acceptedRideTopic
          content-type: application/json
          group: passengers
      kafka:
        binder:
          brokers: "${KAFKA_HOST}:${KAFKA_PORT}"

logging:
  level:
    root: info
    liquibase: error

exception:
  handling:
    include: true
