spring:
  jpa:
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
  settings:
    cab-app-passenger-service:
      uri: http://${PASSENGER_SERVICE_HOST}:${PASSENGER_SERVICE_PORT}/api/v1/passengers
    cab-app-driver-service:
      uri: http://${DRIVER_SERVICE_HOST}:${DRIVER_SERVICE_PORT}/api/v1/drivers
    cab-app-payment-service:
      uri: http://${PAYMENT_SERVICE_HOST}:${PAYMENT_SERVICE_PORT}/api/v1/passenger-payments

logging:
  config: classpath:logback-dev.xml
  level:
    '[by.arvisit.cabapp]': debug
    '[org.springframework.security]': debug
    '[org.springframework.web]': debug
