spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 3000
        response-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    root: info

server:
  forward-headers-strategy: framework
