spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    root: info

server:
  forward-headers-strategy: framework
