spring:
  jpa:
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
  settings:
    cab-app-passenger-service:
      uri: http://localhost:8480/api/v1/passengers
    cab-app-driver-service:
      uri: http://localhost:8480/api/v1/drivers
    cab-app-rides-service:
      uri: http://localhost:8480/api/v1/rides

logging:
  config: classpath:logback-dev.xml
  level:
    '[by.arvisit.cabapp]': debug
    '[org.springframework.security]': debug
    '[org.springframework.web]': debug
