spring:
  jpa:
    show-sql: true
    properties:
      '[hibernate.format_sql]': true

logging:
  config: classpath:logback-dev.xml
  level:
    '[by.arvisit.cabapp]': debug
    '[org.springframework.security]': debug
    '[org.springframework.web]': debug
