spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  cloud:
    function:
      definition: notifyAboutRideAcceptance
    stream:
      bindings:
        notifyAboutRideAcceptance-in-0:
          destination: acceptedRideTopic
          content-type: application/json
          group: passengers
      kafka:
        binder:
          brokers: "${KAFKA_HOST}:${KAFKA_PORT}"
          enable-observation: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans

logging:
  level:
    root: info
    liquibase: error

exception:
  handling:
    include: true
