spring:
  jpa:
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
  settings:
    cab-app-rides-service:
      uri: http://${RIDES_SERVICE_HOST}:${RIDES_SERVICE_PORT}/api/v1/rides

logging:
  config: classpath:logback-dev.xml
  level:
    '[by.arvisit.cabapp]': debug
    '[org.springframework.security]': debug
    '[org.springframework.web]': debug
