spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  data:
    web:
      pageable:
        max-page-size: 50

  cloud:
    function:
      definition: notifyDriversAboutNewRide;notifyAboutRideCancellation
    stream:
      bindings:
        notifyDriversAboutNewRide-in-0:
          destination: newRideTopic
          content-type: application/json
          group: drivers
        notifyAboutRideCancellation-in-0:
          destination: canceledRideTopic
          content-type: application/json
          group: drivers
      kafka:
        binder:
          brokers: localhost:29092

logging:
  level:
    root: info
    liquibase: error

exception:
  handling:
    include: true
