name: Java CI with Maven

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  INNER_DEPENDENCIES: |
    cab-app-common/
    cab-app-exception-handling-starter/

jobs:
  test:
    runs-on: ubuntu-latest
    name: Maven Test
    steps:
    - uses: actions/checkout@v4
      with:
         fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
         java-version: '21'
         distribution: 'temurin'
         cache: maven
    - name: Push or pull-request to non-protected branches
      if: ${{ (github.event_name == 'push' &&
                github.ref != 'refs/heads/dev' &&
                github.ref != 'refs/heads/main') ||
              (github.event_name == 'pull_request' &&
                github.base_ref != 'dev' &&
                github.base_ref != 'main') }}
      run: |
        flag=0
        for i in $INNER_DEPENDENCIES; do
            if [[ $(git diff --quiet HEAD origin/dev -- "$i") -ne 0 ]]; then
                echo "Changes in inner dependency: $i while working in non-protected branch"
                flag=1
                break
            fi
        done
        if [[ $flag -eq 1 ]]; then
            mvn test
        else
            for i in $INNER_DEPENDENCIES; do
                mvn install --file "$i"pom.xml
            done
            for i in *service/; do
                git diff --quiet HEAD origin/dev -- "$i" || { echo "Changes in $i while working in non-protected branch";
                    mvn test --file "$i"pom.xml; }
            done
        fi
    - name: Push or pull-request to dev branch
      if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/dev') ||
              (github.event_name == 'pull_request' && github.base_ref == 'dev') }}
      run: |
        flag=0
        for i in $INNER_DEPENDENCIES; do
            if [[ $(git diff --quiet HEAD origin/dev -- "$i") -ne 0 ]]; then
                echo "Changes in inner dependency: $i while applying to dev"
                flag=1
                break
            fi
        done
        if [[ $flag -eq 1 ]]; then
            mvn verify
        else
            for i in $INNER_DEPENDENCIES; do
                mvn install --file "$i"pom.xml
            done
            for i in *service/; do
                git diff --quiet HEAD origin/dev -- "$i" || { echo "Changes in $i while applying to dev";
                    mvn verify --file "$i"pom.xml; }
            done
        fi
    - name: Push or pull-request to main branch
      if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
              (github.event_name == 'pull_request' && github.base_ref == 'main') }}
      run: |
        flag=0
        for i in $INNER_DEPENDENCIES; do
            if [[ $(git diff --quiet HEAD origin/main -- "$i") -ne 0 ]]; then
                echo "Changes in inner dependency: $i while applying to main"
                flag=1
                break
            fi
        done
        if [[ $flag -eq 1 ]]; then
            mvn verify
        else
            for i in $INNER_DEPENDENCIES; do
                mvn install --file "$i"pom.xml
            done
            for i in *service/; do
                git diff --quiet HEAD origin/main -- "$i" || { echo "Changes in $i while applying to main";
                    mvn verify --file "$i"pom.xml; }
            done
        fi
